workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE != 'merge_request_event'

variables:
  GIT_DEPTH: "1"


printenv:
  stage: .pre
  script:
    - printenv

gcc_musl:
  image: alpine
  stage: test
  before_script:
    - apk add --no-cache build-base
  script:
    - ./scripts/test_ci.sh
#  artifacts:
#    paths:
#      - mybinary


gcc_glibc:
  image: gcc
  stage: test
  script:
    - ./scripts/test_ci.sh


#deploy:
#  stage: deploy
#  script: echo "Define your deployment script!"
#  environment: production
