# https://github.com/rokoDev/rabbit/blob/master/.circleci/config.yml
#    https://discuss.circleci.com/t/is-it-possible-to-build-and-test-my-project-in-docker-container-with-s390x-architecture/44077
#       s390x: Installing packages takes too long, use rokoDev's docker image
#
# - https://circleci.com/docs/variables/
# - https://circleci.com/developer/images?imageType=machine
# - https://circleci.com/docs/using-docker/

# These (and other) variables are wrong when using GitLab:
# CIRCLE_REPOSITORY_URL  : empty
# CIRCLE_PROJECT_USERNAME: wrong
# CIRCLE_PROJECT_REPONAME: wrong

version: 2.1


commands:
  docker_build:
    steps:
      - run:
          name: "Checkout sources + Build and test app"
          command: |
            CIRCLE_REPOSITORY_URL='https://gitlab.com/wdlkmpx/unace1'
            docker exec -it WCONTAINER bash -c "
                        set -ex;
                        pwd;
                        git clone --depth 1 --branch ${CIRCLE_BRANCH} ${CIRCLE_REPOSITORY_URL};
                        cd $(basename ${CIRCLE_REPOSITORY_URL});
                        ./scripts/test_ci.sh;
                        "
  docker_build2:
    steps:
      - run:
          name: "Checkout sources + Build and test app"
          command: |
            CIRCLE_REPOSITORY_URL='https://gitlab.com/wdlkmpx/unace1'
            git clone --depth 1 --branch ${CIRCLE_BRANCH} ${CIRCLE_REPOSITORY_URL}
            docker exec -it WCONTAINER mkdir -p /tmp
            docker cp $(basename ${CIRCLE_REPOSITORY_URL}) WCONTAINER:/tmp/
            docker exec -it WCONTAINER bash -c "
                        set -ex;
                        pwd;
                        cd /tmp/$(basename ${CIRCLE_REPOSITORY_URL});
                        ./scripts/test_ci.sh;
                        "


jobs:
  ubuntu_s390x:
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    environment:
      DOCKER_BUILDKIT: 1
    steps:
      - run: printenv
      - run:
          name: Enable run containers with different architectures
          command: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - run:
          name: Run docker container for s390x
          command: docker run -it -d --platform linux/s390x --name WCONTAINER rokodev/ubuntu2204-dev:1.0
#          command: docker run -it -d --platform linux/s390x --name WCONTAINER s390x/ubuntu
#      - run:
#          name: "Install deps"
#          command: docker exec -it WCONTAINER bash -c "
#                        set -ex;
#                        apt update;
#                        apt upgrade -y;
#                        apt-get install -y git build-essential gdb;
#                        "
      - docker_build
#
# gcc 4.7
  gcc_4_7:
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    steps:
      - run: printenv
      - run:
          name: Run docker container for gcc
          command: docker run -it -d --name WCONTAINER gcc:4.7
      - docker_build2


workflows:
  build_and_test:
    jobs:
      - ubuntu_s390x:
          filters:
            branches:
              only:
                - master
      - gcc_4_7:
          filters:
            branches:
              only:
                - master
